lib/live_menu_order_web/router.ex
defmodule LiveMenuOrderWeb.Router do
  use LiveMenuOrderWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LiveMenuOrderWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LiveMenuOrderWeb do
    pipe_through :browser

    get "/", PageController, :index
    live "/admin/menus", AdminMenuLive.Index, :index
    live "/admin/menus/new", AdminMenuLive.Index, :new
    live "/admin/menus/:id/edit", AdminMenuLive.Index, :edit

    live "/admin/menus/:id", AdminMenuLive.Show, :show
    live "/admin/menus/:id/show/edit", AdminMenuLive.Show, :edit

    live "/admin/tables", TableLive.Index, :index
    live "/admin/tables/new", TableLive.Index, :new
    live "/admin/tables/:id/edit", TableLive.Index, :edit

    live "/admin/tables/:id", TableLive.Show, :show
    live "/admin/tables/:id/show/edit", TableLive.Show, :edit

    live "/table/:table_id/menu", MenuLive.Index, :index
    live "/table/:table_id/order", OrderLive.Show, :show
    live "/menu/:id", MenuLive.Show, :show
    live "/menu/:menu_id/table/:table_id", MenuLive.ShowTable, :show

    live "/admin/orders", OrderLive.Index, :index
    live "/admin/orders/new", OrderLive.Index, :new
    live "/admin/orders/:id/edit", OrderLive.Index, :edit

    live "/admin/orders/:id", OrderLive.Show, :show
    live "/admin/orders/:id/show/edit", OrderLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", LiveMenuOrderWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: LiveMenuOrderWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/live_menu_order_web/live/admin_menu_live/form_component.ex
defmodule LiveMenuOrderWeb.AdminMenuLive.FormComponent do
  use LiveMenuOrderWeb, :live_component

  alias LiveMenuOrder.Menus

  @impl true
  def update(%{menu: menu} = assigns, socket) do
    changeset = Menus.change_menu(menu)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"menu" => menu_params}, socket) do
    changeset =
      socket.assigns.menu
      |> Menus.change_menu(menu_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"menu" => menu_params}, socket) do
    save_menu(socket, socket.assigns.action, menu_params)
  end

  defp save_menu(socket, :edit, menu_params) do
    case Menus.update_menu(socket.assigns.menu, menu_params) do
      {:ok, _menu} ->
        {:noreply,
         socket
         |> put_flash(:info, "Menu updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_menu(socket, :new, menu_params) do
    case Menus.create_menu(menu_params) do
      {:ok, _menu} ->
        {:noreply,
         socket
         |> put_flash(:info, "Menu created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/live_menu_order_web/live/admin_menu_live/index.ex
defmodule LiveMenuOrderWeb.AdminMenuLive.Index do
  use LiveMenuOrderWeb, :live_view

  alias LiveMenuOrder.Menus
  alias LiveMenuOrder.Menus.Menu

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :menus, list_menus())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Menu")
    |> assign(:menu, Menus.get_menu!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Menu")
    |> assign(:menu, %Menu{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Menus")
    |> assign(:menu, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    menu = Menus.get_menu!(id)
    {:ok, _} = Menus.delete_menu(menu)

    {:noreply, assign(socket, :menus, list_menus())}
  end

  defp list_menus do
    Menus.list_menus()
  end
end

lib/live_menu_order_web/live/admin_menu_live/show.ex
defmodule LiveMenuOrderWeb.AdminMenuLive.Show do
  use LiveMenuOrderWeb, :live_view

  alias LiveMenuOrder.Menus

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:menu, Menus.get_menu!(id))}
  end

  defp page_title(:show), do: "Show Menu"
  defp page_title(:edit), do: "Edit Menu"
end

lib/live_menu_order_web/live/live_helpers.ex
defmodule LiveMenuOrderWeb.LiveHelpers do
  import Phoenix.LiveView
  import Phoenix.LiveView.Helpers

  alias Phoenix.LiveView.JS

  @doc """
  Renders a live component inside a modal.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <.modal return_to={Routes.admin_menu_index_path(@socket, :index)}>
        <.live_component
          module={LiveMenuOrderWeb.AdminMenuLive.FormComponent}
          id={@menu.id || :new}
          title={@page_title}
          action={@live_action}
          return_to={Routes.admin_menu_index_path(@socket, :index)}
          menu: @menu
        />
      </.modal>
  """
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="phx-modal fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="phx-modal-content fade-in-scale"
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <%= live_patch "✖",
            to: @return_to,
            id: "close",
            class: "phx-modal-close",
            phx_click: hide_modal()
          %>
        <% else %>
          <a id="close" href="#" class="phx-modal-close" phx-click={hide_modal()}>✖</a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content", transition: "fade-out-scale")
  end
end

lib/live_menu_order_web/live/menu_live/index.ex
defmodule LiveMenuOrderWeb.MenuLive.Index do
  use LiveMenuOrderWeb, :live_view

  alias LiveMenuOrder.Menus
  alias LiveMenuOrder.Orders
  alias LiveMenuOrder.Orders.Order
  alias LiveMenuOrder.Tables
  alias LiveMenuOrder.Tables.Table
  alias LiveMenuOrder.DynamicSupervisor
  alias CartState
  alias LastAddedState
  alias Phoenix.LiveView.JS

  @impl true
  def mount(%{"table_id" => table_id}, _session, socket) do
    if connected?(socket), do: LiveMenuOrderWeb.Endpoint.subscribe(table_topic(table_id))

    {:ok, socket}
  end

  @impl true
  def handle_params(%{"table_id" => table_id}, _session, socket) do
    table = %Table{id: table_id}
    order = Tables.get_single_order_by_table(table_id)

    order =
      case order do
        nil -> %Order{table_id: String.to_integer(table_id)}
        _ -> order
      end

    cart_name = via_tuple(:table, table_id)
    last_added_name = via_tuple(:last_added, table_id)

    DynamicSupervisor.start_child({CartState, %{initial_value: %{}, name: cart_name}})
    DynamicSupervisor.start_child({LastAddedState, last_added_name})

    cart = CartState.value(cart_name)
    last_added = LastAddedState.value(last_added_name)

    total =
      for {_id, item} <- order.order, reduce: 0.0 do
        acc ->
          item["total_price"] + acc
      end

    total =
      for {_id, item} <- cart, reduce: total do
        acc ->
          item["total_price"] + acc
      end

    {:noreply,
     assign(socket,
       menus: list_menus(),
       cart: cart,
       total: :erlang.float_to_binary(total, [decimals: 2]),
       table: table,
       order: order,
       last_added: last_added
     )}
  end

  @impl true
  def handle_event("add", value, socket) do
    cart_name = via_tuple(:table, socket.assigns.table.id)
    CartState.add(cart_name, value)
    cart_state = CartState.value(cart_name)

    last_added_name = via_tuple(:last_added, socket.assigns.table.id)
    LastAddedState.update(last_added_name, value)
    last_added = LastAddedState.value(last_added_name)

    LiveMenuOrderWeb.Endpoint.broadcast(
      table_topic(socket.assigns.table.id),
      "update_state",
      %{cart_state: cart_state, last_added: last_added}
    )

    {:noreply, socket}
  end

  @impl true
  def handle_event("remove", value, socket) do
    cart_name = via_tuple(:table, socket.assigns.table.id)
    CartState.remove(cart_name, value)
    cart_state = CartState.value(cart_name)

    last_added_name = via_tuple(:last_added, socket.assigns.table.id)
    last_added = LastAddedState.value(last_added_name)

    LiveMenuOrderWeb.Endpoint.broadcast(
      table_topic(socket.assigns.table.id),
      "update_state",
      %{cart_state: cart_state, last_added: last_added}
    )

    {:noreply, socket}
  end

  @impl true
  def handle_event("save_order", %{"order" => order}, socket) do
    {:ok, order} =
      case socket.assigns.order.id do
        nil ->
          Orders.create_order(%{
            order: order,
            total: socket.assigns.total,
            table_id: socket.assigns.table.id
          })

        _ ->
          temp =
            Map.merge(socket.assigns.order.order, order, fn _k, v1, v2 ->
              Map.merge(v1, v2, fn key, vv1, vv2 ->
                case key do
                  "count" -> vv1 + vv2
                  "total_price" -> vv1 + vv2
                  _ -> vv1
                end
              end)
            end)

          Orders.update_order(socket.assigns.order, %{
            order: temp,
            total: socket.assigns.total,
            table_id: socket.assigns.table.id
          })
      end

    LiveMenuOrderWeb.Endpoint.broadcast(table_topic(socket.assigns.table.id), "save_order", nil)

    cart_name = via_tuple(:table, socket.assigns.table.id)
    CartState.clear(cart_name)

    {:noreply,
     socket
     |> assign(cart: [])
     |> assign(total: 0)
     |> push_redirect(to: Routes.order_show_path(socket, :show, order.table_id))}
  end

  @impl true
  def handle_info(%{event: "update_state", payload: payload}, socket) do
    %{cart_state: state, last_added: last_added} = payload

    total =
      for {_id, item} <- socket.assigns.order.order, reduce: 0.0 do
        acc ->
          item["total_price"] + acc
      end

    total =
      for {_id, item} <- state, reduce: total do
        acc ->
          item["total_price"] + acc
      end

    total = :erlang.float_to_binary(total, [decimals: 2])

    {:noreply,
     socket
     |> push_event("update_state", %{total: total})
     |> assign(:cart, state)
     |> assign(:last_added, last_added)
     |> assign(:total, total)}
  end

  @impl true
  def handle_info(%{event: "save_order"}, socket) do
    last_added_name = via_tuple(:last_added, socket.assigns.table.id)
    LastAddedState.clear(last_added_name)

    {:noreply,
     socket
     |> put_flash(:info, "Order sent.")
     |> push_patch(to: Routes.menu_index_path(socket, :index, socket.assigns.table.id))}
  end

  @impl true
  def handle_info(%{event: "kick"}, socket) do
    {:noreply,
     socket
     |> put_flash(:info, "Order closed.")
     |> push_patch(to: Routes.menu_index_path(socket, :index, socket.assigns.table.id))}
  end

  defp list_menus do
    Menus.list_menus()
  end

  defp table_topic(table_id) do
    "table:" <> table_id
  end

  defp via_tuple(:table, table_id) do
    {:via, Registry, {LiveMenuOrder.Registry, "table:" <> table_id}}
  end

  defp via_tuple(:last_added, table_id) do
    {:via, Registry, {LiveMenuOrder.Registry, "last_added:" <> table_id}}
  end
end

lib/live_menu_order_web/live/menu_live/show.ex
defmodule LiveMenuOrderWeb.MenuLive.Show do
  use LiveMenuOrderWeb, :live_view

  alias LiveMenuOrder.Menus

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:menu, Menus.get_menu!(id))}
  end

  defp page_title(:show), do: "Show Menu"
end

lib/live_menu_order_web/live/menu_live/show_table.ex
defmodule LiveMenuOrderWeb.MenuLive.ShowTable do
  use LiveMenuOrderWeb, :live_view

  alias LiveMenuOrder.Menus
  alias LiveMenuOrder.DynamicSupervisor
  alias CartState
  alias LastAddedState

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"table_id" => table_id, "menu_id" => menu_id}, _, socket) do
    cart_name = via_tuple(:table, table_id)
    last_added_name = via_tuple(:last_added, table_id)

    DynamicSupervisor.start_child({CartState, %{initial_value: %{}, name: cart_name}})
    DynamicSupervisor.start_child({LastAddedState, last_added_name})

    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:menu, Menus.get_menu!(menu_id))
     |> assign(:table_id, table_id)}
  end

  @impl true
  def handle_event("add", value, socket) do
    cart_name = via_tuple(:table, socket.assigns.table_id)
    CartState.add(cart_name, value)
    cart_state = CartState.value(cart_name)

    last_added_name = via_tuple(:last_added, socket.assigns.table_id)
    LastAddedState.update(last_added_name, value)
    last_added = LastAddedState.value(last_added_name)

    LiveMenuOrderWeb.Endpoint.broadcast(
      table_topic(socket.assigns.table_id),
      "update_state",
      %{cart_state: cart_state, last_added: last_added}
    )

    {:noreply,
     socket
     |> put_flash(:info, "Order added.")}
  end

  defp page_title(:show), do: "Show Menu"

  defp table_topic(table_id) do
    "table:" <> table_id
  end

  defp via_tuple(:table, table_id) do
    {:via, Registry, {LiveMenuOrder.Registry, "table:" <> table_id}}
  end

  defp via_tuple(:last_added, table_id) do
    {:via, Registry, {LiveMenuOrder.Registry, "last_added:" <> table_id}}
  end
end

lib/live_menu_order_web/live/order_live/form_component.ex
defmodule LiveMenuOrderWeb.OrderLive.FormComponent do
  use LiveMenuOrderWeb, :live_component

  alias LiveMenuOrder.Orders

  @impl true
  def update(%{order: order} = assigns, socket) do
    changeset = Orders.change_order(order)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"order" => order_params}, socket) do
    changeset =
      socket.assigns.order
      |> Orders.change_order(order_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"order" => order_params}, socket) do
    save_order(socket, socket.assigns.action, order_params)
  end

  defp save_order(socket, :edit, order_params) do
    case Orders.update_order(socket.assigns.order, order_params) do
      {:ok, _order} ->
        {:noreply,
         socket
         |> put_flash(:info, "Order updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_order(socket, :new, order_params) do
    case Orders.create_order(order_params) do
      {:ok, _order} ->
        {:noreply,
         socket
         |> put_flash(:info, "Order created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/live_menu_order_web/live/menu_live/index.html.heex
<h1 class="my-4">Menu</h1>

<table class="table select-none">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody id="menus">
    <%= for menu <- @menus do %>
      <tr id={"menu-#{menu.id}"}>
        <td>
          <span><%= live_redirect menu.name, to: Routes.menu_show_table_path(@socket, :show, menu, @table) %></span>
        </td>
        <td>RM <%= menu.price %></td>
        <td>
          <svg
            phx-click="add"
            phx-value-menu_id={menu.id}
            phx-value-menu_name={menu.name}
            phx-value-menu_price={menu.price}
            xmlns="http://www.w3.org/2000/svg"
            class="icon icon-tabler icon-tabler-circle-plus my-4 mx-auto"
            width="32"
            height="32"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="#00b341"
            fill="none"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
            <circle cx="12" cy="12" r="9" />
            <line x1="9" y1="12" x2="15" y2="12" />
            <line x1="12" y1="9" x2="12" y2="15" />
          </svg>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div
  id="cart-bottom-sheet"
  x-data="cart"
  class="w-full h-full px-12 py-2 fixed bottom-0 left-0 bg-sky-300 overflow-auto select-none"
>
  <div class="w-4/5 m-auto grid grid-cols-2 gap-2 h-36">
    <h3 class="mb-0">Total</h3>
    <h3 class="text-center mb-0" id="total" phx-hook="TotalNumber" data-total={@total}>RM <%= @total %></h3>
    <span id="last_added" phx-hook="LastAdded"><%= @last_added %></span>
    <button class="col-start-2 text-center m-0" phx-click={JS.push("save_order", value: %{order: @cart})}>Save</button>
  </div>
  <h2 class="my-4">Cart</h2>
  <table class="table mb-0">
    <thead>
      <tr>
        <th>Name</th>
        <th>Count</th>
        <th>Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody id="cart">
      <%= for {_id, item} <- @cart do %>
        <tr>
          <td>
            <span><%= live_redirect item["menu_name"], to: Routes.menu_show_path(@socket, :show, item["menu_id"]) %></span>
          </td>
          <td><%= item["count"] %></td>
          <td>RM <%= item["total_price"] %></td>
          <td class="flex">
            <svg
              phx-click="remove"
              phx-value-menu_id={item["menu_id"]}
              phx-value-menu_name={item["menu_name"]}
              xmlns="http://www.w3.org/2000/svg"
              class="icon icon-tabler icon-tabler-circle-minus my-4"
              width="32"
              height="32"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="#ff2825"
              fill="none"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
              <circle cx="12" cy="12" r="9" />
              <line x1="9" y1="12" x2="15" y2="12" />
            </svg>
            <svg
              phx-click="add"
              phx-value-menu_id={item["menu_id"]}
              phx-value-menu_name={item["menu_name"]}
              xmlns="http://www.w3.org/2000/svg"
              class="icon icon-tabler icon-tabler-circle-plus my-4"
              width="32"
              height="32"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="#00b341"
              fill="none"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
              <circle cx="12" cy="12" r="9" />
              <line x1="9" y1="12" x2="15" y2="12" />
              <line x1="12" y1="9" x2="12" y2="15" />
            </svg>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

lib/live_menu_order_web/live/menu_live/show.html.heex
<h1>Show Menu</h1>

<ul>
  <li>
    <strong>Name:</strong>
    <%= @menu.name %>
  </li>
</ul>

lib/live_menu_order_web/live/menu_live/show_table.html.heex
<h1>Show Menu</h1>

<ul>
  <li>
    <strong>Name:</strong>
    <%= @menu.name %>
  </li>
</ul>

<button 
  phx-click="add"
  phx-value-menu_id={@menu.id}
  phx-value-menu_name={@menu.name}
  phx-value-menu_price={@menu.price}
>
  Add
</button>

<%= live_redirect to: Routes.menu_index_path(@socket, :index, @table_id) do %>
  Back to menu
<% end %>